# Generated by Django 4.2.1 on 2023-05-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_bankentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankentity',
            old_name='requentuse',
            new_name='frequent',
        ),
    ]
