# Generated by Django 4.2.1 on 2023-05-12 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_rename_requentuse_bankentity_frequent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankEntity',
        ),
    ]
