# Generated by Django 4.2.1 on 2023-05-12 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_delete_bankentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'The name of the bank entity needs to be at least 2 characters')])),
                ('frequent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bill')),
            ],
        ),
    ]
